# Pandas 한번에 제대로 배우기




---



In [1]:
import numpy as np
import pandas as pd
pd.__version__

'1.1.3'

## Pandas 객체


### Series 객체

In [2]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0]) #인덱스와 함께 데이터가 저장
print(s)

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64


In [3]:
s.values #값만 추출

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
s[1]

0.25

In [6]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [7]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0], 
              index=['a','b','c','d','e'])
print(s)

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64


In [8]:
s['c']

0.5

In [9]:
s[['c','d','e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [10]:
'b' in s

True

In [11]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index=[2,4,6,8,10])
print(s)


2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64


In [12]:
s[4]

0.25

In [13]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [14]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
s.value_counts()

1.00    1
0.75    1
0.50    1
0.25    1
0.00    1
dtype: int64

In [16]:
s.isin([0.25,0.75]) #불리언 형태로 반환

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [17]:
pop_tuple = {'서울특별시': 9720846,
            '부산광역시': 3404423,
            '인천광역시': 2947217,
            '대구광역시': 2427954,
            '대전광역시': 1471040,
            '광주광역시': 1455048}
print(pop_tuple)
population = pd.Series(pop_tuple)
population

{'서울특별시': 9720846, '부산광역시': 3404423, '인천광역시': 2947217, '대구광역시': 2427954, '대전광역시': 1471040, '광주광역시': 1455048}


서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [18]:
population['서울특별시']

9720846

In [19]:
population['서울특별시':'인천광역시'] #슬라이싱

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [20]:
pd.DataFrame([{'A':2, 'B':4, 'D':3}, {'A':4, 'B':5, 'C':7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [21]:
pd.DataFrame(np.random.rand(5,5),
            columns=['A','B','C','D','E'],
            index=[1,2,3,4,5])

A         B         C         D         E
1  0.714518  0.182614  0.996320  0.941522  0.923640
2  0.229156  0.118409  0.660016  0.290822  0.981491
3  0.526268  0.343838  0.228155  0.584027  0.230684
4  0.668488  0.274976  0.679723  0.535741  0.792894
5  0.849673  0.150987  0.056631  0.994804  0.694654

In [22]:
male_tuple = {'서울특별시': 4732275,
              '부산광역시': 1668618,
              '인천광역시': 1476813,
              '대구광역시': 1198815,
              '대전광역시': 734441,
              '광주광역시': 720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [23]:
female_tuple = {'서울특별시': 4988571,
              '부산광역시': 1735805,
              '인천광역시': 1470404,
              '대구광역시': 1229139,
              '대전광역시': 736599,
              '광주광역시': 734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [24]:
korea_df = pd.DataFrame({'인구수': population,
                         '남자인구수': male,
                         '여자인구수': female})
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [25]:
#속성
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [26]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [27]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [28]:
korea_df['서울특별시':'인천광역시']    

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

### Index 객체


In [29]:
idx = pd.Index([2,4,6,8,10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [30]:
idx[1]

4

In [31]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [32]:
idx[-1::]

Int64Index([10], dtype='int64')

In [33]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [34]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산

In [35]:
idx1 = pd.Index([1,2,4,6,8])
idx2 = pd.Index([2,4,5,6,7])
print(idx1.append(idx2))
print(idx1.difference(idx2)) # 차집합
print(idx1 - idx2)
print(idx1.intersection(idx2)) # 교집합
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx1 | idx2)
print(idx1.delete(0))
print(idx1.drop(1))
print(idx1 ^ idx2) #여집합

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')




---



## 인덱싱(Indexing)

In [36]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index=['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [37]:
s['b']

0.25

In [38]:
'b' in s

True

In [39]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [40]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [41]:
s['f'] = 1.25 #새로운값 추가
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [42]:
s['a':'d'] # s[0:4]와 같음

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [43]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [44]:
s[(s > 0.4) & (s < 0.8)]

c    0.50
d    0.75
dtype: float64

In [45]:
s[['a','c','e']] #원하는 부분만 추출하기

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [46]:
s = pd.Series(['a','b','c','d','e'],
              index=[1,3,5,7,9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [47]:
s[1]

'a'

In [48]:
s[2:4]

5    c
7    d
dtype: object

In [49]:
s.iloc[1] #숫자1인 인덱스값을 추출하는 것이 아닌 인덱스위치에 있는 값 출력 

'b'

In [50]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [51]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [52]:
s.reindex(range(10), method='bfill') #NaN값에 이전값을 채워주기

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱


In [53]:
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [54]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [55]:
korea_df.남자인구수 #위와 똑같은 결과 출력

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [56]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [57]:
korea_df['남여비율'] = (korea_df['남자인구수'] * 100 / korea_df['여자인구수'])
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [58]:
korea_df.values

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [59]:
korea_df.T #전치행렬

서울특별시         부산광역시         인천광역시         대구광역시         대전광역시  \
인구수    9.720846e+06  3.404423e+06  2.947217e+06  2.427954e+06  1.471040e+06   
남자인구수  4.732275e+06  1.668618e+06  1.476813e+06  1.198815e+06  7.344410e+05   
여자인구수  4.988571e+06  1.735805e+06  1.470404e+06  1.229139e+06  7.365990e+05   
남여비율   9.486234e+01  9.612935e+01  1.004359e+02  9.753291e+01  9.970703e+01   

              광주광역시  
인구수    1.455048e+06  
남자인구수  7.200600e+05  
여자인구수  7.349880e+05  
남여비율   9.796895e+01

In [60]:
korea_df.values[0] #서울특별시만 출력

array([9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [61]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

In [62]:
korea_df.loc[:'인천광역시',:'남자인구수']

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [63]:
korea_df.loc[(korea_df['여자인구수']>=1000000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907

In [64]:
korea_df.loc[(korea_df.인구수 < 2000000)]

인구수   남자인구수   여자인구수       남여비율
대전광역시  1471040  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [65]:
korea_df.loc[(korea_df.인구수 > 2500000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [66]:
korea_df.loc[(korea_df.남여비율 >= 100)]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [67]:
korea_df.loc[(korea_df.인구수 >= 2500000) & (korea_df.남여비율 > 100)]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [68]:
korea_df.iloc[:3, :2]

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [69]:
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [70]:
idx_tuples = [('서울특별시', 2010), ('서울특별시', 2020),
              ('부산광역시', 2010), ('부산광역시', 2020), 
              ('인천광역시', 2010), ('인천광역시', 2020),
              ('대구광역시', 2010), ('대구광역시', 2020),
              ('대전광역시', 2010), ('대전광역시', 2020),
              ('광주광역시', 2010), ('광주광역시', 2020)]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [71]:
pop_tuples = [10312345, 9720846,
              2567910, 3404423,
              2758296, 2947217,
              2511676, 2427954,
              1503664, 1471040,
              1454636, 1455048]

population = pd.Series(pop_tuples, index=idx_tuples)
population

(서울특별시, 2010)    10312345
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [72]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [73]:
population = population.reindex(midx)
population

서울특별시  2010    10312345
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [74]:
population[:, 2010]

서울특별시    10312345
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [75]:
population['대전광역시',:]

2010    1503664
2020    1471040
dtype: int64

In [76]:
korea_mdf = population.unstack()
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312345  9720846
인천광역시   2758296  2947217

In [77]:
korea_mdf.stack()

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312345
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [78]:
male_tuple = [5111259, 4732275,
              1773170, 1668618,
              1390356, 1476813,
              1255245, 1198815,
              753648, 734441,
              721780, 720060]
male_tuple

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [79]:
korea_mdf = pd.DataFrame({'총인구수': population, 
                          '남자인구수': male_tuple})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312345  5111259
      2020   9720846  4732275
부산광역시 2010   2567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [80]:
female_tuples = [5201286, 4988571,
                 1794740, 1735805,
                 1367940, 1470404,
                 1256431, 1229139,
                 750016, 736599,
                 732856, 734988]
female_tuples

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [81]:
korea_mdf = pd.DataFrame({'총인구수': population, 
                          '남자인구수': male_tuple,
                          '여자인구수': female_tuples})
korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  10312345  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   2567910  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [82]:
ratio = korea_mdf['남자인구수'] * 100 / korea_mdf['여자인구수']
ratio.unstack()

2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [83]:
korea_mdf = pd.DataFrame({'총인구수': population, 
                          '남자인구수': male_tuple,
                          '여자인구수': female_tuples,
                          '남여비율': ratio})
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
서울특별시 2010  10312345  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [84]:
df = pd.DataFrame(np.random.rand(6,3), 
                  index=[['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]],
                  columns=['c1', 'c2', 'c3'])
df

c1        c2        c3
a 1  0.161291  0.681321  0.955741
  2  0.669501  0.608117  0.351129
b 1  0.538348  0.624281  0.440793
  2  0.480364  0.014208  0.599790
c 1  0.362284  0.980553  0.741977
  2  0.584631  0.648016  0.031017

In [85]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]]) #배열로 인덱스 만들기

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [86]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2), ('c', 1), ('c', 2)]) #튜플로 인덱스 만들기

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [87]:
pd.MultiIndex.from_product([['a','b','c'], [1, 2]]) #곱으로 인덱스 만들기

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [88]:
pd.MultiIndex(levels=[['a','b','c'], [1, 2]],
              codes=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]]) #위치값의 인덱스를 코드로 나타냄

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [89]:
population

서울특별시  2010    10312345
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [90]:
population.index.names = ['행정구역', '년도'] #인덱스 이름 설정하기
population.unstack()

년도         2010     2020
행정구역                    
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312345  9720846
인천광역시   2758296  2947217

In [91]:
idx = pd.MultiIndex.from_product([['a','b','c'], [1,2]], 
                                 names=['name1','name2'])
col = pd.MultiIndex.from_product([['c1', 'c2', 'c3'], [1, 2]],
                                 names=['col_name1', 'col_name2'])
data = np.round(np.random.randn(6, 6), 2)
mdf = pd.DataFrame(data, index=idx, columns=col)
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -0.45  1.98 -0.84  0.36 -0.88  1.10
      2     -0.17 -0.43  0.56 -1.14  0.48  0.25
b     1      0.77 -0.83 -0.43  0.45 -0.71  0.82
      2     -1.01  0.47 -0.73 -1.31 -1.31  1.31
c     1     -0.86  1.31 -1.64  0.13 -0.73 -0.41
      2      0.25  0.40  0.12 -0.66  0.34 -1.47

In [92]:
mdf['c2']

col_name2       1     2
name1 name2            
a     1     -0.84  0.36
      2      0.56 -1.14
b     1     -0.43  0.45
      2     -0.73 -1.31
c     1     -1.64  0.13
      2      0.12 -0.66

#### 인덱싱 및 슬라이싱

In [93]:
population['인천광역시', 2010]

2758296

In [94]:
population[:, 2010]

행정구역
서울특별시    10312345
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [95]:
population[population > 3000000]

행정구역   년도  
서울특별시  2010    10312345
       2020     9720846
부산광역시  2020     3404423
dtype: int64

In [96]:
population[['대구광역시','대전광역시']]

행정구역   년도  
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [97]:
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -0.45  1.98 -0.84  0.36 -0.88  1.10
      2     -0.17 -0.43  0.56 -1.14  0.48  0.25
b     1      0.77 -0.83 -0.43  0.45 -0.71  0.82
      2     -1.01  0.47 -0.73 -1.31 -1.31  1.31
c     1     -0.86  1.31 -1.64  0.13 -0.73 -0.41
      2      0.25  0.40  0.12 -0.66  0.34 -1.47

In [98]:
mdf['c2', 1]

name1  name2
a      1       -0.84
       2        0.56
b      1       -0.43
       2       -0.73
c      1       -1.64
       2        0.12
Name: (c2, 1), dtype: float64

In [99]:
mdf.iloc[:3, :4] #정수 인덱스

col_name1      c1          c2      
col_name2       1     2     1     2
name1 name2                        
a     1     -0.45  1.98 -0.84  0.36
      2     -0.17 -0.43  0.56 -1.14
b     1      0.77 -0.83 -0.43  0.45

In [100]:
mdf.loc[:, ('c2', 1)]

name1  name2
a      1       -0.84
       2        0.56
b      1       -0.43
       2       -0.73
c      1       -1.64
       2        0.12
Name: (c2, 1), dtype: float64

In [101]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:, 2], idx_slice[:, 2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2                  
a     2     -0.43 -1.14  0.25
b     2      0.47 -1.31  1.31
c     2      0.40 -0.66 -1.47

#### 다중 인덱스 재정렬

In [102]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [103]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312345  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [104]:
#korea_mdf['서울특별시':'인천광역시']
korea_mdf = korea_mdf.sort_index()
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312345  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [105]:
korea_mdf['서울특별시':'인천광역시']

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312345  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [106]:
korea_mdf.unstack(level=0)

총인구수                                                 남자인구수           \
행정구역    광주광역시    대구광역시    대전광역시    부산광역시     서울특별시    인천광역시   광주광역시    대구광역시   
년도                                                                             
2010  1454636  2511676  1503664  2567910  10312345  2758296  721780  1255245   
2020  1455048  2427954  1471040  3404423   9720846  2947217  720060  1198815   

                       ...   여자인구수                                  남여비율  \
행정구역   대전광역시    부산광역시  ...   대전광역시    부산광역시    서울특별시    인천광역시      광주광역시   
년도                     ...                                                 
2010  753648  1773170  ...  750016  1794740  5201286  1367940  98.488653   
2020  734441  1668618  ...  736599  1735805  4988571  1470404  97.968946   

                                                               
행정구역      대구광역시       대전광역시      부산광역시      서울특별시       인천광역시  
년도                                                             
2010  99.905606  100.484256  98.798155  98.269140  101.638668  
2020  97.532907   99.707032  96.129346  94.862336  100.435867  

[2 rows x 24 columns]

In [107]:
korea_mdf.unstack(level=1)

총인구수             남자인구수             여자인구수                 남여비율  \
년도         2010     2020     2010     2020     2010     2020        2010   
행정구역                                                                       
광주광역시   1454636  1455048   721780   720060   732856   734988   98.488653   
대구광역시   2511676  2427954  1255245  1198815  1256431  1229139   99.905606   
대전광역시   1503664  1471040   753648   734441   750016   736599  100.484256   
부산광역시   2567910  3404423  1773170  1668618  1794740  1735805   98.798155   
서울특별시  10312345  9720846  5111259  4732275  5201286  4988571   98.269140   
인천광역시   2758296  2947217  1390356  1476813  1367940  1470404  101.638668   

                   
년도           2020  
행정구역               
광주광역시   97.968946  
대구광역시   97.532907  
대전광역시   99.707032  
부산광역시   96.129346  
서울특별시   94.862336  
인천광역시  100.435867

In [108]:
korea_mdf.stack()

행정구역   년도         
광주광역시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남여비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남여비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남여비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남여비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남여비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남여비율     9.970703e+01
부산광역시  2010  총인구수     2.567910e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남여비율     9.879815e+01
 

In [109]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312345  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [110]:
idx_flat = korea_mdf.reset_index(level=0)
idx_flat

행정구역      총인구수    남자인구수    여자인구수        남여비율
년도                                                 
2010  광주광역시   1454636   721780   732856   98.488653
2020  광주광역시   1455048   720060   734988   97.968946
2010  대구광역시   2511676  1255245  1256431   99.905606
2020  대구광역시   2427954  1198815  1229139   97.532907
2010  대전광역시   1503664   753648   750016  100.484256
2020  대전광역시   1471040   734441   736599   99.707032
2010  부산광역시   2567910  1773170  1794740   98.798155
2020  부산광역시   3404423  1668618  1735805   96.129346
2010  서울특별시  10312345  5111259  5201286   98.269140
2020  서울특별시   9720846  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2947217  1476813  1470404  100.435867

In [111]:
idx_flat = korea_mdf.reset_index(level=1)
idx_flat

년도      총인구수    남자인구수    여자인구수        남여비율
행정구역                                               
광주광역시  2010   1454636   721780   732856   98.488653
광주광역시  2020   1455048   720060   734988   97.968946
대구광역시  2010   2511676  1255245  1256431   99.905606
대구광역시  2020   2427954  1198815  1229139   97.532907
대전광역시  2010   1503664   753648   750016  100.484256
대전광역시  2020   1471040   734441   736599   99.707032
부산광역시  2010   2567910  1773170  1794740   98.798155
부산광역시  2020   3404423  1668618  1735805   96.129346
서울특별시  2010  10312345  5111259  5201286   98.269140
서울특별시  2020   9720846  4732275  4988571   94.862336
인천광역시  2010   2758296  1390356  1367940  101.638668
인천광역시  2020   2947217  1476813  1470404  100.435867

In [112]:
idx_flat = korea_mdf.reset_index(level=(0, 1))
idx_flat

행정구역    년도      총인구수    남자인구수    여자인구수        남여비율
0   광주광역시  2010   1454636   721780   732856   98.488653
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   2567910  1773170  1794740   98.798155
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10312345  5111259  5201286   98.269140
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [113]:
idx_flat.set_index(['행정구역', '년도'])

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312345  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

## 데이터 연산

In [114]:
s = pd.Series(np.random.randint(0, 10, 5))
s

0    0
1    7
2    1
3    6
4    7
dtype: int32

In [115]:
df = pd.DataFrame(np.random.randint(0, 10, (3,3)),
                  columns=['A', 'B', 'C'])
df

A  B  C
0  6  5  9
1  2  3  3
2  5  8  3

In [116]:
np.exp(s)

0       1.000000
1    1096.633158
2       2.718282
3     403.428793
4    1096.633158
dtype: float64

In [117]:
np.cos(df * np.pi / 4)

A         B         C
0 -1.836970e-16 -0.707107  0.707107
1  6.123234e-17 -0.707107 -0.707107
2 -7.071068e-01  1.000000 -0.707107

In [118]:
s1 = pd.Series([1, 3, 5, 7, 9], index=[0, 1, 2, 3, 4])
s2 = pd.Series([2, 4, 6, 8, 10], index=[1, 2, 3, 4, 5])
s1 + s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [119]:
s1.add(s2, fill_value=0) #NaN 대신에 0을 넣는다

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [120]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3,3)),
                   columns=list('ACD'))
df1

A   C   D
0   2  19  17
1  19  17   6
2  14  17  11

In [121]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5,5)),
                   columns=list('BAECD'))
df2

B   A   E   C   D
0   4   8   5  10  12
1  12  18  10   3  13
2   1   0  11   0   0
3   3  19   3   4   1
4  17   6   0   0  18

In [122]:
df1 + df2

A   B     C     D   E
0  10.0 NaN  29.0  29.0 NaN
1  37.0 NaN  20.0  19.0 NaN
2  14.0 NaN  17.0  11.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [123]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value = fvalue)

A          B          C          D          E
0  10.000000  17.555556  29.000000  29.000000  18.555556
1  37.000000  25.555556  20.000000  19.000000  23.555556
2  14.000000  14.555556  17.000000  11.000000  24.555556
3  32.555556  16.555556  17.555556  14.555556  16.555556
4  19.555556  30.555556  13.555556  31.555556  13.555556

### 연산자 범용 함수


#### add()

In [124]:
a = np.random.randint(1, 10, size=(3,3))
a

array([[6, 1, 3],
       [9, 5, 4],
       [5, 8, 9]])

In [125]:
a + a[0]

array([[12,  2,  6],
       [15,  6,  7],
       [11,  9, 12]])

In [126]:
df = pd.DataFrame(a, columns=list('ABC'))
df

A  B  C
0  6  1  3
1  9  5  4
2  5  8  9

In [127]:
df + df.iloc[2]

A   B   C
0  11   9  12
1  14  13  13
2  10  16  18

In [128]:
df.add(df.iloc[0])

A  B   C
0  12  2   6
1  15  6   7
2  11  9  12

#### sub() / subtract()

In [129]:
a

array([[6, 1, 3],
       [9, 5, 4],
       [5, 8, 9]])

In [130]:
a - a[0]

array([[ 0,  0,  0],
       [ 3,  4,  1],
       [-1,  7,  6]])

In [131]:
df

A  B  C
0  6  1  3
1  9  5  4
2  5  8  9

In [132]:
df - df.iloc[0]

A  B  C
0  0  0  0
1  3  4  1
2 -1  7  6

In [133]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1  3  4  1
2 -1  7  6

In [134]:
df.subtract(df['B'], axis=0) #axis=0은 행방향으로 동작, 작업결과가 행으로 나타남, 책을 위로 쌓아 정리하는 것과 같음

A  B  C
0  5  0  2
1  4  0 -1
2 -3  0  1

#### mul() / multply()




In [135]:
a

array([[6, 1, 3],
       [9, 5, 4],
       [5, 8, 9]])

In [136]:
a * a[0]

array([[36,  1,  9],
       [54,  5, 12],
       [30,  8, 27]])

In [137]:
df

A  B  C
0  6  1  3
1  9  5  4
2  5  8  9

In [138]:
df * df.iloc[1]

A   B   C
0  54   5  12
1  81  25  16
2  45  40  36

In [139]:
df.mul(df.iloc[1])

A   B   C
0  54   5  12
1  81  25  16
2  45  40  36

In [140]:
df.multiply(df.iloc[1])

A   B   C
0  54   5  12
1  81  25  16
2  45  40  36

#### truediv() /  div() / divide() / floordiv()

In [141]:
a

array([[6, 1, 3],
       [9, 5, 4],
       [5, 8, 9]])

In [142]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [1.5       , 5.        , 1.33333333],
       [0.83333333, 8.        , 3.        ]])

In [143]:
df

A  B  C
0  6  1  3
1  9  5  4
2  5  8  9

In [144]:
df / df.iloc[0]

A    B         C
0  1.000000  1.0  1.000000
1  1.500000  5.0  1.333333
2  0.833333  8.0  3.000000

In [145]:
df.truediv(df.iloc[0])

A    B         C
0  1.000000  1.0  1.000000
1  1.500000  5.0  1.333333
2  0.833333  8.0  3.000000

In [146]:
df.div(df.iloc[1])

A    B     C
0  0.666667  0.2  0.75
1  1.000000  1.0  1.00
2  0.555556  1.6  2.25

In [147]:
df.divide(df.iloc[2])

A      B         C
0  1.2  0.125  0.333333
1  1.8  0.625  0.444444
2  1.0  1.000  1.000000

In [148]:
a // a[0]

array([[1, 1, 1],
       [1, 5, 1],
       [0, 8, 3]], dtype=int32)

In [149]:
df.floordiv(df.iloc[0])

A  B  C
0  1  1  1
1  1  5  1
2  0  8  3

#### mod()

In [150]:
a

array([[6, 1, 3],
       [9, 5, 4],
       [5, 8, 9]])

In [151]:
a % a[0]

array([[0, 0, 0],
       [3, 0, 1],
       [5, 0, 0]], dtype=int32)

In [152]:
df

A  B  C
0  6  1  3
1  9  5  4
2  5  8  9

In [153]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  3  0  1
2  5  0  0

#### pow()

In [154]:
a

array([[6, 1, 3],
       [9, 5, 4],
       [5, 8, 9]])

In [155]:
a ** a[0]

array([[ 46656,      1,     27],
       [531441,      5,     64],
       [ 15625,      8,    729]], dtype=int32)

In [156]:
df.pow(df.iloc[0])

A  B    C
0   46656  1   27
1  531441  5   64
2   15625  8  729

In [157]:
row = df.iloc[0, ::2]
row

A    6
C    3
Name: 0, dtype: int32

In [158]:
df - row

A   B    C
0  0.0 NaN  0.0
1  3.0 NaN  1.0
2 -1.0 NaN  6.0

### 정렬(Sort)

In [159]:
s = pd.Series(range(5), index=['A', 'D', 'B', 'C', 'E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [160]:
s.sort_index() #인덱스별 정렬

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [161]:
s.sort_values() #값으로 정렬

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [162]:
df = pd.DataFrame(np.random.randint(0, 10, (4,4)),
                  index = [2, 4, 1, 3],
                  columns = list('BDAC'))
df

B  D  A  C
2  4  7  8  3
4  9  5  8  7
1  7  9  0  0
3  6  7  6  7

In [163]:
df.sort_index() #인덱스별 정렬

B  D  A  C
1  7  9  0  0
2  4  7  8  3
3  6  7  6  7
4  9  5  8  7

In [164]:
df.sort_index(axis = 1) #축을 열로 지정하여 ABCD순으로 나옴

A  B  C  D
2  8  4  3  7
4  8  9  7  5
1  0  7  0  9
3  6  6  7  7

In [165]:
# df.sort_values() 2차원이므로 column(열)을 하나 지정해줘야 함
df.sort_values(by = ['A', 'B']) # A 정렬 후 B 정렬

B  D  A  C
1  7  9  0  0
3  6  7  6  7
2  4  7  8  3
4  9  5  8  7

In [166]:
df.sort_values(by = 'C')

B  D  A  C
1  7  9  0  0
2  4  7  8  3
4  9  5  8  7
3  6  7  6  7

### 순위(Ranking)


In [167]:
s = pd.Series([-2, 4, 7, 3, 0, 7, 5, -4, 2, 6])
s

0   -2
1    4
2    7
3    3
4    0
5    7
6    5
7   -4
8    2
9    6
dtype: int64

In [168]:
s.rank()

0    2.0
1    6.0
2    9.5
3    5.0
4    3.0
5    9.5
6    7.0
7    1.0
8    4.0
9    8.0
dtype: float64

In [169]:
s.rank(method = 'first') #테이블 내의 위치에 따라 순위 지정

0     2.0
1     6.0
2     9.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

In [170]:
s.rank(method = 'max') #같은 값을 가지는 그룹을 높은 순위로 지정

0     2.0
1     6.0
2    10.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

### 고성능 연산

In [171]:
nrows, ncols = 100000, 100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows,ncols)) for i in range(4))

In [172]:
%timeit df1 + df2 + df3 + df4

141 ms ± 6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [173]:
%timeit pd.eval('df1 + df2 + df3 + df4')

64.3 ms ± 3.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [174]:
%timeit df1 * df2 / (-df3 * df4)

209 ms ± 13.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [175]:
%timeit pd.eval('df1 * df2 / (-df3 * df4)')

69.5 ms ± 5.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [176]:
%timeit (df1 < df2) & (df2 <= df3) & (df3 != df4)

111 ms ± 4.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [177]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3) & (df3 != df4)')

78.3 ms ± 5.98 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [178]:
df = pd.DataFrame(np.random.rand(100000, 5), columns = ['A', 'B', 'C', 'D', 'E'])
df.head()

A         B         C         D         E
0  0.433561  0.375184  0.518330  0.796590  0.253303
1  0.083542  0.559377  0.646741  0.485924  0.680087
2  0.787437  0.241985  0.608625  0.616036  0.974208
3  0.049714  0.519067  0.825190  0.198028  0.622756
4  0.773522  0.032311  0.622187  0.355784  0.391708

In [179]:
%timeit df['A'] + df['B'] / df['C'] - df['D'] * df['E']

4.43 ms ± 671 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [180]:
%timeit pd.eval('df.A + df.B /  df.C - df.D * df.E')

4.73 ms ± 526 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [181]:
%timeit df.eval('A + B / C - D + E')

7.25 ms ± 951 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [182]:
df.eval('R = A + B / C - D * E', inplace=True)
df.head()

A         B         C         D         E         R
0  0.433561  0.375184  0.518330  0.796590  0.253303  0.955615
1  0.083542  0.559377  0.646741  0.485924  0.680087  0.617988
2  0.787437  0.241985  0.608625  0.616036  0.974208  0.584883
3  0.049714  0.519067  0.825190  0.198028  0.622756  0.555418
4  0.773522  0.032311  0.622187  0.355784  0.391708  0.686089

In [183]:
col_mean = df.mean(1)
df['A'] + col_mean

0        0.988992
1        0.595818
2        1.422967
3        0.511410
4        1.250456
           ...   
99995    1.183372
99996    1.009129
99997    1.080368
99998    3.349077
99999    1.311012
Length: 100000, dtype: float64

In [184]:
 df.eval('A + @col_mean')

0        0.988992
1        0.595818
2        1.422967
3        0.511410
4        1.250456
           ...   
99995    1.183372
99996    1.009129
99997    1.080368
99998    3.349077
99999    1.311012
Length: 100000, dtype: float64

In [185]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]

A         B         C         D         E         R
0      0.433561  0.375184  0.518330  0.796590  0.253303  0.955615
15     0.038092  0.201186  0.765893  0.569079  0.826120 -0.169354
16     0.120395  0.155855  0.721343  0.833829  0.600549 -0.164297
40     0.128214  0.270657  0.896234  0.123384  0.407690  0.379906
43     0.248948  0.121247  0.618656  0.966926  0.658492 -0.191781
...         ...       ...       ...       ...       ...       ...
99966  0.129317  0.499371  0.781161  0.347560  0.821011  0.483234
99972  0.298891  0.198794  0.596913  0.815754  0.876710 -0.083252
99975  0.225395  0.091173  0.705964  0.732200  0.031563  0.331431
99982  0.438381  0.275618  0.624288  0.262798  0.568049  0.730590
99997  0.490851  0.352515  0.923630  0.104114  0.885688  0.780302

[12770 rows x 6 columns]

In [186]:
pd.eval('df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]')

A         B         C         D         E         R
0      0.433561  0.375184  0.518330  0.796590  0.253303  0.955615
15     0.038092  0.201186  0.765893  0.569079  0.826120 -0.169354
16     0.120395  0.155855  0.721343  0.833829  0.600549 -0.164297
40     0.128214  0.270657  0.896234  0.123384  0.407690  0.379906
43     0.248948  0.121247  0.618656  0.966926  0.658492 -0.191781
...         ...       ...       ...       ...       ...       ...
99966  0.129317  0.499371  0.781161  0.347560  0.821011  0.483234
99972  0.298891  0.198794  0.596913  0.815754  0.876710 -0.083252
99975  0.225395  0.091173  0.705964  0.732200  0.031563  0.331431
99982  0.438381  0.275618  0.624288  0.262798  0.568049  0.730590
99997  0.490851  0.352515  0.923630  0.104114  0.885688  0.780302

[12770 rows x 6 columns]

In [187]:
df.query('(A < 0.5) and (B < 0.5) and (C > 0.5)') #query는 eval보다 간단히 표현

A         B         C         D         E         R
0      0.433561  0.375184  0.518330  0.796590  0.253303  0.955615
15     0.038092  0.201186  0.765893  0.569079  0.826120 -0.169354
16     0.120395  0.155855  0.721343  0.833829  0.600549 -0.164297
40     0.128214  0.270657  0.896234  0.123384  0.407690  0.379906
43     0.248948  0.121247  0.618656  0.966926  0.658492 -0.191781
...         ...       ...       ...       ...       ...       ...
99966  0.129317  0.499371  0.781161  0.347560  0.821011  0.483234
99972  0.298891  0.198794  0.596913  0.815754  0.876710 -0.083252
99975  0.225395  0.091173  0.705964  0.732200  0.031563  0.331431
99982  0.438381  0.275618  0.624288  0.262798  0.568049  0.730590
99997  0.490851  0.352515  0.923630  0.104114  0.885688  0.780302

[12770 rows x 6 columns]

In [188]:
col_means = df['D'].mean()
df[(df.A < col_means) & (df.B < col_means)]

A         B         C         D         E          R
0      0.433561  0.375184  0.518330  0.796590  0.253303   0.955615
13     0.284435  0.173069  0.411087  0.459696  0.539475   0.457445
15     0.038092  0.201186  0.765893  0.569079  0.826120  -0.169354
16     0.120395  0.155855  0.721343  0.833829  0.600549  -0.164297
17     0.463425  0.394765  0.168208  0.479110  0.991704   2.335175
...         ...       ...       ...       ...       ...        ...
99982  0.438381  0.275618  0.624288  0.262798  0.568049   0.730590
99985  0.051999  0.314957  0.372016  0.551316  0.537495   0.602292
99989  0.246051  0.153743  0.414031  0.698498  0.941528  -0.040271
99997  0.490851  0.352515  0.923630  0.104114  0.885688   0.780302
99998  0.392218  0.319067  0.019980  0.348303  0.460465  16.201123

[25223 rows x 6 columns]

In [189]:
df.query('A < @col_means and B < @col_means') # @는 외부변수 접근표시

A         B         C         D         E          R
0      0.433561  0.375184  0.518330  0.796590  0.253303   0.955615
13     0.284435  0.173069  0.411087  0.459696  0.539475   0.457445
15     0.038092  0.201186  0.765893  0.569079  0.826120  -0.169354
16     0.120395  0.155855  0.721343  0.833829  0.600549  -0.164297
17     0.463425  0.394765  0.168208  0.479110  0.991704   2.335175
...         ...       ...       ...       ...       ...        ...
99982  0.438381  0.275618  0.624288  0.262798  0.568049   0.730590
99985  0.051999  0.314957  0.372016  0.551316  0.537495   0.602292
99989  0.246051  0.153743  0.414031  0.698498  0.941528  -0.040271
99997  0.490851  0.352515  0.923630  0.104114  0.885688   0.780302
99998  0.392218  0.319067  0.019980  0.348303  0.460465  16.201123

[25223 rows x 6 columns]

## 데이터 결합

### Concat() / Append()

In [190]:
s1 = pd.Series(['a', 'b'], index=[1, 2])
s2 = pd.Series(['c', 'd'], index=[3, 4])
pd.concat([s1, s2])

1    a
2    b
3    c
4    d
dtype: object

In [191]:
def create_df(cols, idx):
    data = {c: [str(c.lower()) + str(i) for i in idx] for c in cols}
    return pd.DataFrame(data, idx)

In [192]:
df1 = create_df('AB', [1, 2])
df1

A   B
1  a1  b1
2  a2  b2

In [193]:
df2 = create_df('AB', [3, 4])
df2

A   B
3  a3  b3
4  a4  b4

In [194]:
pd.concat([df1, df2])

A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [195]:
df3 = create_df('AB', [0, 1])
df3

A   B
0  a0  b0
1  a1  b1

In [196]:
df4 = create_df('CD', [0, 1])
df4

C   D
0  c0  d0
1  c1  d1

In [197]:
pd.concat([df3, df4])

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [198]:
#pd.concat([df1, df3], verify_integrity=True) #오버랩되기 때문에 error 발생

In [199]:
pd.concat([df1, df3], ignore_index=True) #강제로 합치기

A   B
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

In [200]:
pd.concat([df1, df3], keys=['X', 'Y'])

A   B
X 1  a1  b1
  2  a2  b2
Y 0  a0  b0
  1  a1  b1

In [201]:
df5 = create_df('ABC', [1, 2])
df6 = create_df('BCD', [3, 4])
pd.concat([df5, df6])

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [202]:
pd.concat([df5, df6], join='inner')

B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [203]:
df5.append(df6)

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [204]:
pd.concat([df3, df4])

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [205]:
pd.concat([df3, df4], axis=1) #axis=1은 작업 결과가 옆으로 나타남

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1

### 병합과 조인

In [207]:
df1 = pd.DataFrame({'학생': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '학과': ['경영학과', '교육학과', '컴퓨터학과', '통계학과']})
df1

학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유신   통계학과

In [208]:
df2 = pd.DataFrame({'학생': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '입학년도': [2012, 2016, 2019, 2020]})
df2

학생  입학년도
0  홍길동  2012
1  이순신  2016
2  임꺽정  2019
3  김유신  2020

In [209]:
df3 = pd.merge(df1, df2) #데이터프레임 병합
df3

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [210]:
df4 = pd.DataFrame({'학과': ['경영학과', '교육학과', '켬퓨터학과', '통계학과'],
                    '학과장': ['황희', '장영실', '안창호', '정약용']})
df4

학과  학과장
0   경영학과   황희
1   교육학과  장영실
2  켬퓨터학과  안창호
3   통계학과  정약용

In [211]:
pd.merge(df3, df4)

학생    학과  입학년도  학과장
0  홍길동  경영학과  2012   황희
1  이순신  교육학과  2016  장영실
2  김유신  통계학과  2020  정약용

In [212]:
df5 = pd.DataFrame({'학과': ['경영학과', '교육학과', '교육학과', '컴퓨터학과', '컴퓨터학과', '통계학과'],
                    '과목': ['경영개론', '기초수학', '물리학', '프로그래밍', '운영체제', '확률론']})
df5

학과     과목
0   경영학과   경영개론
1   교육학과   기초수학
2   교육학과    물리학
3  컴퓨터학과  프로그래밍
4  컴퓨터학과   운영체제
5   통계학과    확률론

In [213]:
pd.merge(df1, df5) #학과를 기준으로 병합

학생     학과     과목
0  홍길동   경영학과   경영개론
1  이순신   교육학과   기초수학
2  이순신   교육학과    물리학
3  임꺽정  컴퓨터학과  프로그래밍
4  임꺽정  컴퓨터학과   운영체제
5  김유신   통계학과    확률론

In [265]:
pd.merge(df1, df2, on='학생') #on은 학생을 기준으로 한 것

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [215]:
df6 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '성적': ['A', 'A+', 'B', 'A+']})
df6

이름  성적
0  홍길동   A
1  이순신  A+
2  임꺽정   B
3  김유신  A+

In [218]:
#pd.merge(df1, df6)
pd.merge(df1, df6, left_on='학생', right_on='이름')

학생     학과   이름  성적
0  홍길동   경영학과  홍길동   A
1  이순신   교육학과  이순신  A+
2  임꺽정  컴퓨터학과  임꺽정   B
3  김유신   통계학과  김유신  A+

In [220]:
pd.merge(df1, df6, left_on='학생', right_on='이름').drop('이름', axis=1)

학생     학과  성적
0  홍길동   경영학과   A
1  이순신   교육학과  A+
2  임꺽정  컴퓨터학과   B
3  김유신   통계학과  A+

In [221]:
mdf1 = df1.set_index('학생')
mdf2 = df2.set_index('학생')

In [222]:
mdf1

학과
학생        
홍길동   경영학과
이순신   교육학과
임꺽정  컴퓨터학과
김유신   통계학과

In [223]:
mdf2

입학년도
학생       
홍길동  2012
이순신  2016
임꺽정  2019
김유신  2020

In [224]:
pd.merge(mdf1, mdf2, left_index=True, right_index=True)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [225]:
mdf1.join(mdf2)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [226]:
pd.merge(mdf1, df6, left_index=True, right_on='이름')

학과   이름  성적
0   경영학과  홍길동   A
1   교육학과  이순신  A+
2  컴퓨터학과  임꺽정   B
3   통계학과  김유신  A+

In [229]:
df7 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정'],
                    '주문음식': ['햄버거', '피자', '짜장면']})
df7

이름 주문음식
0  홍길동  햄버거
1  이순신   피자
2  임꺽정  짜장면

In [230]:
df8 = pd.DataFrame({'이름': ['홍길동', '이순신', '김유신'],
                    '주문음료': ['콜라', '사이다', '커피']})
df8

이름 주문음료
0  홍길동   콜라
1  이순신  사이다
2  김유신   커피

In [231]:
pd.merge(df7, df8)

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [232]:
pd.merge(df7, df8, how='inner')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [233]:
pd.merge(df7, df8, how='outer') #outer는 다 포함

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN
3  김유신  NaN   커피

In [234]:
pd.merge(df7, df8, how='left') #df7가 기준

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN

In [235]:
pd.merge(df7, df8, how='right') #df8이 기준

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  김유신  NaN   커피

In [236]:
df9 = pd.DataFrame({'이름':['홍길동', '이순신', '임꺽정', '김유신'],
                    '순위':[3,2,4,1]})
df9

이름  순위
0  홍길동   3
1  이순신   2
2  임꺽정   4
3  김유신   1

In [237]:
df10= pd.DataFrame({'이름':['홍길동', '이순신', '임꺽정', '김유신'],
                    '순위':[4,1,3,2]})
df10

이름  순위
0  홍길동   4
1  이순신   1
2  임꺽정   3
3  김유신   2

In [239]:
pd.merge(df9, df10, on='이름', suffixes=["_인기", "_성적"])

이름  순위_인기  순위_성적
0  홍길동      3      4
1  이순신      2      1
2  임꺽정      4      3
3  김유신      1      2

## 데이터 집계와 그룹 연산


#### 집계 연산(Aggregation)


In [243]:
df = pd.DataFrame([[1, 1.2, np.nan],
              [2.4, 5.5, 4.2],
              [np.nan, np.nan, np.nan],
              [0.44, -3.1, -4.1]],
             index=[1, 2, 3, 4],
             columns=['A','B','C'])
df


A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [244]:
df.head(2) #앞부분 2행 출력

A    B    C
1  1.0  1.2  NaN
2  2.4  5.5  4.2

In [245]:
df.tail(2) #뒷부분 2행 출력

A    B    C
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [246]:
df.describe()

A     B         C
count  3.000000  3.00  2.000000
mean   1.280000  1.20  0.050000
std    1.009554  4.30  5.868986
min    0.440000 -3.10 -4.100000
25%    0.720000 -0.95 -2.025000
50%    1.000000  1.20  0.050000
75%    1.700000  3.35  2.125000
max    2.400000  5.50  4.200000

In [247]:
print(df)
print(np.argmin(df), np.argmax(df)) #열방향으로 최소값, 최대값의 색인 위치 argmin,argmax

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
2 2


In [248]:
print(df)
print(df.idxmin()) #행방향으로 최소값, 최대값의 색인 위치 idxmin, idxmax
print(df.idxmax())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    4
B    4
C    4
dtype: int64
A    2
B    2
C    2
dtype: int64


In [249]:
print(df)
print(df.std()) #표본분산
print(df.var()) #분산

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.009554
B    4.300000
C    5.868986
dtype: float64
A     1.0192
B    18.4900
C    34.4450
dtype: float64


In [250]:
print(df)
print(df.skew()) #왜도
print(df.kurt()) #첨도

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.15207
B    0.00000
C        NaN
dtype: float64
A   NaN
B   NaN
C   NaN
dtype: float64


In [251]:
print(df)
print(df.sum()) #합, NaN 스킵
print(df.cumsum()) #누적합

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    3.84
B    3.60
C    0.10
dtype: float64
      A    B    C
1  1.00  1.2  NaN
2  3.40  6.7  4.2
3   NaN  NaN  NaN
4  3.84  3.6  0.1


In [253]:
print(df)
print(df.prod()) #곱
print(df.cumprod()) #누적 곱

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A     1.056
B   -20.460
C   -17.220
dtype: float64
       A      B      C
1  1.000   1.20    NaN
2  2.400   6.60   4.20
3    NaN    NaN    NaN
4  1.056 -20.46 -17.22


In [254]:
df.diff()

A    B   C
1  NaN  NaN NaN
2  1.4  4.3 NaN
3  NaN  NaN NaN
4  NaN  NaN NaN

In [255]:
df.quantile()

A    1.00
B    1.20
C    0.05
Name: 0.5, dtype: float64

In [256]:
df.pct_change()

A         B        C
1       NaN       NaN      NaN
2  1.400000  3.583333      NaN
3  0.000000  0.000000  0.00000
4 -0.816667 -1.563636 -1.97619

In [257]:
df.corr() #상관관계 분석

A         B    C
A  1.000000  0.970725  1.0
B  0.970725  1.000000  1.0
C  1.000000  1.000000  1.0

In [260]:
df.corrwith(df.B) #B값을 기준으로 상관관계 분석

A    0.970725
B    1.000000
C    1.000000
dtype: float64

In [261]:
df.cov() #공분산

A       B       C
A  1.0192   4.214   8.134
B  4.2140  18.490  35.690
C  8.1340  35.690  34.445

In [262]:
df['B'].unique()

array([ 1.2,  5.5,  nan, -3.1])

In [263]:
df['A'].value_counts()

0.44    1
2.40    1
1.00    1
Name: A, dtype: int64

### GroupBy 연산

In [267]:
df = pd.DataFrame({'c1': ['a', 'a', 'b', 'b', 'c','d', 'b'],
                   'c2': ['A', 'B', 'B', 'A', 'D', 'C', 'C'],
                   'c3': np.random.randint(7),
                   'c4': np.random.random(7)})
df

c1 c2  c3        c4
0  a  A   4  0.010118
1  a  B   4  0.253330
2  b  B   4  0.942642
3  b  A   4  0.017330
4  c  D   4  0.396507
5  d  C   4  0.200739
6  b  C   4  0.494195

In [268]:
df.dtypes

c1     object
c2     object
c3      int64
c4    float64
dtype: object

In [270]:
df['c3'].groupby(df['c1']).mean() #c1을 기준으로 c3의 mean값 계산

c1
a    4
b    4
c    4
d    4
Name: c3, dtype: int64

In [271]:
df['c4'].groupby(df['c2']).std() #c2를 기준으로 c4의 표준편차 계산

c2
A    0.005100
B    0.487417
C    0.207505
D         NaN
Name: c4, dtype: float64

In [272]:
df['c4'].groupby([df['c1'], df['c2']]).mean() #c1을 첫번째, c2를 두번째 기준으로 c4의 평균 계산

c1  c2
a   A     0.010118
    B     0.253330
b   A     0.017330
    B     0.942642
    C     0.494195
c   D     0.396507
d   C     0.200739
Name: c4, dtype: float64

In [273]:
df['c4'].groupby([df['c1'], df['c2']]).mean().unstack()

c2         A         B         C         D
c1                                        
a   0.010118  0.253330       NaN       NaN
b   0.017330  0.942642  0.494195       NaN
c        NaN       NaN       NaN  0.396507
d        NaN       NaN  0.200739       NaN

In [274]:
df.groupby('c1').mean() #c1을 기준으로 평균계산

c3        c4
c1              
a    4  0.131724
b    4  0.484723
c    4  0.396507
d    4  0.200739

In [275]:
df.groupby(['c1', 'c2']).mean() #c1,c2를 기준으로 평균계산

c3        c4
c1 c2              
a  A    4  0.010118
   B    4  0.253330
b  A    4  0.017330
   B    4  0.942642
   C    4  0.494195
c  D    4  0.396507
d  C    4  0.200739

In [276]:
df.groupby(['c1', 'c2']).size() #c1,c2 기준으로 크기 계산

c1  c2
a   A     1
    B     1
b   A     1
    B     1
    C     1
c   D     1
d   C     1
dtype: int64

In [278]:
df.groupby('c1')

In [277]:
for c1, group in df.groupby('c1'):
    print(c1)
    print(group)

a
  c1 c2  c3        c4
0  a  A   4  0.010118
1  a  B   4  0.253330
b
  c1 c2  c3        c4
2  b  B   4  0.942642
3  b  A   4  0.017330
6  b  C   4  0.494195
c
  c1 c2  c3        c4
4  c  D   4  0.396507
d
  c1 c2  c3        c4
5  d  C   4  0.200739


In [279]:
for (c1,c2), group in df.groupby(['c1','c2']):
    print((c1,c2))
    print(group)

('a', 'A')
  c1 c2  c3        c4
0  a  A   4  0.010118
('a', 'B')
  c1 c2  c3       c4
1  a  B   4  0.25333
('b', 'A')
  c1 c2  c3       c4
3  b  A   4  0.01733
('b', 'B')
  c1 c2  c3        c4
2  b  B   4  0.942642
('b', 'C')
  c1 c2  c3        c4
6  b  C   4  0.494195
('c', 'D')
  c1 c2  c3        c4
4  c  D   4  0.396507
('d', 'C')
  c1 c2  c3        c4
5  d  C   4  0.200739


In [281]:
df.groupby(['c1', 'c2'])[['c4']].mean()

c1  c2
a   A     0.010118
    B     0.253330
b   A     0.017330
    B     0.942642
    C     0.494195
c   D     0.396507
d   C     0.200739
Name: c4, dtype: float64

In [282]:
df.groupby('c1')['c3'].quantile()

c1
a    4.0
b    4.0
c    4.0
d    4.0
Name: c3, dtype: float64

In [283]:
df.groupby('c1')['c3'].count()

c1
a    2
b    3
c    1
d    1
Name: c3, dtype: int64

In [284]:
df.groupby('c1')['c4'].median()

c1
a    0.131724
b    0.494195
c    0.396507
d    0.200739
Name: c4, dtype: float64

In [285]:
df.groupby('c1')['c4'].std()

c1
a    0.171977
b    0.462729
c         NaN
d         NaN
Name: c4, dtype: float64

In [287]:
df.groupby(['c1', 'c2'])['c4'].agg(['mean', 'min', 'max']) #c1과 c2를 기준으로 c4에 대한 전체집계값을 여러 개 출력

mean       min       max
c1 c2                              
a  A   0.010118  0.010118  0.010118
   B   0.253330  0.253330  0.253330
b  A   0.017330  0.017330  0.017330
   B   0.942642  0.942642  0.942642
   C   0.494195  0.494195  0.494195
c  D   0.396507  0.396507  0.396507
d  C   0.200739  0.200739  0.200739

In [289]:
df.groupby(['c1', 'c2'], as_index=False)['c4'].mean() #인덱스 사라지고 하나의 컬럼으로 표시됨

c1 c2        c4
0  a  A  0.010118
1  a  B  0.253330
2  b  A  0.017330
3  b  B  0.942642
4  b  C  0.494195
5  c  D  0.396507
6  d  C  0.200739

In [290]:
df.groupby(['c1', 'c2'], group_keys=False)['c4'].mean()

c1  c2
a   A     0.010118
    B     0.253330
b   A     0.017330
    B     0.942642
    C     0.494195
c   D     0.396507
d   C     0.200739
Name: c4, dtype: float64

In [291]:
def top(df, n=3, column='c1'):
    return df.sort_values(by=column)[-n:]

top(df, n=5) #c1을 기준으로 top 5 출력

c1 c2  c3        c4
2  b  B   4  0.942642
3  b  A   4  0.017330
6  b  C   4  0.494195
4  c  D   4  0.396507
5  d  C   4  0.200739

In [292]:
top(df, n=6, column='c4') #c4를 기준으로 값이 큰 6개 행 출력

c1 c2  c3        c4
3  b  A   4  0.017330
5  d  C   4  0.200739
1  a  B   4  0.253330
4  c  D   4  0.396507
6  b  C   4  0.494195
2  b  B   4  0.942642

In [293]:
df.groupby('c1').apply(top)

c1 c2  c3        c4
c1                      
a  0  a  A   4  0.010118
   1  a  B   4  0.253330
b  2  b  B   4  0.942642
   3  b  A   4  0.017330
   6  b  C   4  0.494195
c  4  c  D   4  0.396507
d  5  d  C   4  0.200739

### 피벗 테이블(Pivot Table)


### 범주형(Categorical) 데이터


## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly