# Pandas 한번에 제대로 배우기




---



In [1]:
import numpy as np
import pandas as pd
pd.__version__

'1.1.3'

## Pandas 객체


### Series 객체

In [2]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0]) #인덱스와 함께 데이터가 저장
print(s)

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64


In [3]:
s.values #값만 추출

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
s[1]

0.25

In [6]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [7]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0], 
              index=['a','b','c','d','e'])
print(s)

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64


In [8]:
s['c']

0.5

In [9]:
s[['c','d','e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [10]:
'b' in s

True

In [11]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index=[2,4,6,8,10])
print(s)


2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64


In [12]:
s[4]

0.25

In [13]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [14]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
s.value_counts()

1.00    1
0.75    1
0.50    1
0.25    1
0.00    1
dtype: int64

In [16]:
s.isin([0.25,0.75]) #불리언 형태로 반환

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [17]:
pop_tuple = {'서울특별시': 9720846,
            '부산광역시': 3404423,
            '인천광역시': 2947217,
            '대구광역시': 2427954,
            '대전광역시': 1471040,
            '광주광역시': 1455048}
print(pop_tuple)
population = pd.Series(pop_tuple)
population

{'서울특별시': 9720846, '부산광역시': 3404423, '인천광역시': 2947217, '대구광역시': 2427954, '대전광역시': 1471040, '광주광역시': 1455048}


서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [18]:
population['서울특별시']

9720846

In [19]:
population['서울특별시':'인천광역시'] #슬라이싱

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [20]:
pd.DataFrame([{'A':2, 'B':4, 'D':3}, {'A':4, 'B':5, 'C':7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [21]:
pd.DataFrame(np.random.rand(5,5),
            columns=['A','B','C','D','E'],
            index=[1,2,3,4,5])

A         B         C         D         E
1  0.860521  0.904202  0.956869  0.548376  0.081094
2  0.399605  0.606282  0.111674  0.827124  0.442018
3  0.757920  0.884664  0.550107  0.211706  0.672020
4  0.065172  0.261142  0.989231  0.195019  0.502399
5  0.928551  0.354419  0.147158  0.296034  0.488917

In [22]:
male_tuple = {'서울특별시': 4732275,
              '부산광역시': 1668618,
              '인천광역시': 1476813,
              '대구광역시': 1198815,
              '대전광역시': 734441,
              '광주광역시': 720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [23]:
female_tuple = {'서울특별시': 4988571,
              '부산광역시': 1735805,
              '인천광역시': 1470404,
              '대구광역시': 1229139,
              '대전광역시': 736599,
              '광주광역시': 734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [24]:
korea_df = pd.DataFrame({'인구수': population,
                         '남자인구수': male,
                         '여자인구수': female})
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [25]:
#속성
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [26]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [27]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [28]:
korea_df['서울특별시':'인천광역시']    

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

### Index 객체


In [29]:
idx = pd.Index([2,4,6,8,10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [30]:
idx[1]

4

In [31]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [32]:
idx[-1::]

Int64Index([10], dtype='int64')

In [33]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [34]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산

In [35]:
idx1 = pd.Index([1,2,4,6,8])
idx2 = pd.Index([2,4,5,6,7])
print(idx1.append(idx2))
print(idx1.difference(idx2)) # 차집합
print(idx1 - idx2)
print(idx1.intersection(idx2)) # 교집합
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx1 | idx2)
print(idx1.delete(0))
print(idx1.drop(1))
print(idx1 ^ idx2) #여집합

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')




---



## 인덱싱(Indexing)

In [36]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index=['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [37]:
s['b']

0.25

In [38]:
'b' in s

True

In [39]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [40]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [41]:
s['f'] = 1.25 #새로운값 추가
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [42]:
s['a':'d'] # s[0:4]와 같음

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [43]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [44]:
s[(s > 0.4) & (s < 0.8)]

c    0.50
d    0.75
dtype: float64

In [45]:
s[['a','c','e']] #원하는 부분만 추출하기

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [46]:
s = pd.Series(['a','b','c','d','e'],
              index=[1,3,5,7,9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [47]:
s[1]

'a'

In [48]:
s[2:4]

5    c
7    d
dtype: object

In [49]:
s.iloc[1] #숫자1인 인덱스값을 추출하는 것이 아닌 인덱스위치에 있는 값 출력 

'b'

In [50]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [51]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [52]:
s.reindex(range(10), method='bfill') #NaN값에 이전값을 채워주기

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱


In [53]:
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [54]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [55]:
korea_df.남자인구수 #위와 똑같은 결과 출력

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [56]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [57]:
korea_df['남여비율'] = (korea_df['남자인구수'] * 100 / korea_df['여자인구수'])
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [58]:
korea_df.values

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [59]:
korea_df.T #전치행렬

서울특별시         부산광역시         인천광역시         대구광역시         대전광역시  \
인구수    9.720846e+06  3.404423e+06  2.947217e+06  2.427954e+06  1.471040e+06   
남자인구수  4.732275e+06  1.668618e+06  1.476813e+06  1.198815e+06  7.344410e+05   
여자인구수  4.988571e+06  1.735805e+06  1.470404e+06  1.229139e+06  7.365990e+05   
남여비율   9.486234e+01  9.612935e+01  1.004359e+02  9.753291e+01  9.970703e+01   

              광주광역시  
인구수    1.455048e+06  
남자인구수  7.200600e+05  
여자인구수  7.349880e+05  
남여비율   9.796895e+01

In [60]:
korea_df.values[0] #서울특별시만 출력

array([9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [61]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

In [62]:
korea_df.loc[:'인천광역시',:'남자인구수']

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [63]:
korea_df.loc[(korea_df['여자인구수']>=1000000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907

In [64]:
korea_df.loc[(korea_df.인구수 < 2000000)]

인구수   남자인구수   여자인구수       남여비율
대전광역시  1471040  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [65]:
korea_df.loc[(korea_df.인구수 > 2500000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [66]:
korea_df.loc[(korea_df.남여비율 >= 100)]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [67]:
korea_df.loc[(korea_df.인구수 >= 2500000) & (korea_df.남여비율 > 100)]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [68]:
korea_df.iloc[:3, :2]

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [69]:
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [70]:
idx_tuples = [('서울특별시', 2010), ('서울특별시', 2020),
              ('부산광역시', 2010), ('부산광역시', 2020), 
              ('인천광역시', 2010), ('인천광역시', 2020),
              ('대구광역시', 2010), ('대구광역시', 2020),
              ('대전광역시', 2010), ('대전광역시', 2020),
              ('광주광역시', 2010), ('광주광역시', 2020)]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [71]:
pop_tuples = [10312345, 9720846,
              2567910, 3404423,
              2758296, 2947217,
              2511676, 2427954,
              1503664, 1471040,
              1454636, 1455048]

population = pd.Series(pop_tuples, index=idx_tuples)
population

(서울특별시, 2010)    10312345
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [72]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [73]:
population = population.reindex(midx)
population

서울특별시  2010    10312345
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [74]:
population[:, 2010]

서울특별시    10312345
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [75]:
population['대전광역시',:]

2010    1503664
2020    1471040
dtype: int64

In [76]:
korea_mdf = population.unstack()
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312345  9720846
인천광역시   2758296  2947217

In [77]:
korea_mdf.stack()

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312345
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [78]:
male_tuple = [5111259, 4732275,
              1773170, 1668618,
              1390356, 1476813,
              1255245, 1198815,
              753648, 734441,
              721780, 720060]
male_tuple

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [79]:
korea_mdf = pd.DataFrame({'총인구수': population, 
                          '남자인구수': male_tuple})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312345  5111259
      2020   9720846  4732275
부산광역시 2010   2567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [80]:
female_tuples = [5201286, 4988571,
                 1794740, 1735805,
                 1367940, 1470404,
                 1256431, 1229139,
                 750016, 736599,
                 732856, 734988]
female_tuples

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [81]:
korea_mdf = pd.DataFrame({'총인구수': population, 
                          '남자인구수': male_tuple,
                          '여자인구수': female_tuples})
korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  10312345  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   2567910  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [82]:
ratio = korea_mdf['남자인구수'] * 100 / korea_mdf['여자인구수']
ratio.unstack()

2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [83]:
korea_mdf = pd.DataFrame({'총인구수': population, 
                          '남자인구수': male_tuple,
                          '여자인구수': female_tuples,
                          '남여비율': ratio})
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
서울특별시 2010  10312345  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [84]:
df = pd.DataFrame(np.random.rand(6,3), 
                  index=[['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]],
                  columns=['c1', 'c2', 'c3'])
df

c1        c2        c3
a 1  0.732627  0.272388  0.357884
  2  0.162495  0.215266  0.725371
b 1  0.152819  0.611187  0.120634
  2  0.273709  0.704801  0.928193
c 1  0.321588  0.731757  0.192709
  2  0.737651  0.979892  0.363854

In [85]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]]) #배열로 인덱스 만들기

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [86]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2), ('c', 1), ('c', 2)]) #튜플로 인덱스 만들기

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [87]:
pd.MultiIndex.from_product([['a','b','c'], [1, 2]]) #곱으로 인덱스 만들기

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [88]:
pd.MultiIndex(levels=[['a','b','c'], [1, 2]],
              codes=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]]) #위치값의 인덱스를 코드로 나타냄

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [89]:
population

서울특별시  2010    10312345
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [90]:
population.index.names = ['행정구역', '년도'] #인덱스 이름 설정하기
population.unstack()

년도         2010     2020
행정구역                    
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312345  9720846
인천광역시   2758296  2947217

In [91]:
idx = pd.MultiIndex.from_product([['a','b','c'], [1,2]], 
                                 names=['name1','name2'])
col = pd.MultiIndex.from_product([['c1', 'c2', 'c3'], [1, 2]],
                                 names=['col_name1', 'col_name2'])
data = np.round(np.random.randn(6, 6), 2)
mdf = pd.DataFrame(data, index=idx, columns=col)
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1      0.47 -1.72  0.66  0.30  2.59  0.60
      2     -0.26  0.47  0.25 -0.19 -0.16  0.98
b     1     -1.11  1.43  0.41 -0.28  0.86  0.56
      2     -0.34 -1.14 -0.17  1.07 -1.47  0.80
c     1      0.02  0.33  0.02  0.25 -0.22  1.60
      2      0.42  0.22 -1.35  1.22 -0.97 -1.98

In [92]:
mdf['c2']

col_name2       1     2
name1 name2            
a     1      0.66  0.30
      2      0.25 -0.19
b     1      0.41 -0.28
      2     -0.17  1.07
c     1      0.02  0.25
      2     -1.35  1.22

#### 인덱싱 및 슬라이싱

In [93]:
population['인천광역시', 2010]

2758296

In [94]:
population[:, 2010]

행정구역
서울특별시    10312345
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [95]:
population[population > 3000000]

행정구역   년도  
서울특별시  2010    10312345
       2020     9720846
부산광역시  2020     3404423
dtype: int64

In [96]:
population[['대구광역시','대전광역시']]

행정구역   년도  
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [97]:
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1      0.47 -1.72  0.66  0.30  2.59  0.60
      2     -0.26  0.47  0.25 -0.19 -0.16  0.98
b     1     -1.11  1.43  0.41 -0.28  0.86  0.56
      2     -0.34 -1.14 -0.17  1.07 -1.47  0.80
c     1      0.02  0.33  0.02  0.25 -0.22  1.60
      2      0.42  0.22 -1.35  1.22 -0.97 -1.98

In [98]:
mdf['c2', 1]

name1  name2
a      1        0.66
       2        0.25
b      1        0.41
       2       -0.17
c      1        0.02
       2       -1.35
Name: (c2, 1), dtype: float64

In [99]:
mdf.iloc[:3, :4] #정수 인덱스

col_name1      c1          c2      
col_name2       1     2     1     2
name1 name2                        
a     1      0.47 -1.72  0.66  0.30
      2     -0.26  0.47  0.25 -0.19
b     1     -1.11  1.43  0.41 -0.28

In [100]:
mdf.loc[:, ('c2', 1)]

name1  name2
a      1        0.66
       2        0.25
b      1        0.41
       2       -0.17
c      1        0.02
       2       -1.35
Name: (c2, 1), dtype: float64

In [101]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:, 2], idx_slice[:, 2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2                  
a     2      0.47 -0.19  0.98
b     2     -1.14  1.07  0.80
c     2      0.22  1.22 -1.98

#### 다중 인덱스 재정렬

In [102]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [103]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312345  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [104]:
#korea_mdf['서울특별시':'인천광역시']
korea_mdf = korea_mdf.sort_index()
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312345  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [105]:
korea_mdf['서울특별시':'인천광역시']

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312345  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [106]:
korea_mdf.unstack(level=0)

총인구수                                                 남자인구수           \
행정구역    광주광역시    대구광역시    대전광역시    부산광역시     서울특별시    인천광역시   광주광역시    대구광역시   
년도                                                                             
2010  1454636  2511676  1503664  2567910  10312345  2758296  721780  1255245   
2020  1455048  2427954  1471040  3404423   9720846  2947217  720060  1198815   

                       ...   여자인구수                                  남여비율  \
행정구역   대전광역시    부산광역시  ...   대전광역시    부산광역시    서울특별시    인천광역시      광주광역시   
년도                     ...                                                 
2010  753648  1773170  ...  750016  1794740  5201286  1367940  98.488653   
2020  734441  1668618  ...  736599  1735805  4988571  1470404  97.968946   

                                                               
행정구역      대구광역시       대전광역시      부산광역시      서울특별시       인천광역시  
년도                                                             
2010  99.905606  100.484256  98.798155  98.269140  101.638668  
2020  97.532907   99.707032  96.129346  94.862336  100.435867  

[2 rows x 24 columns]

In [107]:
korea_mdf.unstack(level=1)

총인구수             남자인구수             여자인구수                 남여비율  \
년도         2010     2020     2010     2020     2010     2020        2010   
행정구역                                                                       
광주광역시   1454636  1455048   721780   720060   732856   734988   98.488653   
대구광역시   2511676  2427954  1255245  1198815  1256431  1229139   99.905606   
대전광역시   1503664  1471040   753648   734441   750016   736599  100.484256   
부산광역시   2567910  3404423  1773170  1668618  1794740  1735805   98.798155   
서울특별시  10312345  9720846  5111259  4732275  5201286  4988571   98.269140   
인천광역시   2758296  2947217  1390356  1476813  1367940  1470404  101.638668   

                   
년도           2020  
행정구역               
광주광역시   97.968946  
대구광역시   97.532907  
대전광역시   99.707032  
부산광역시   96.129346  
서울특별시   94.862336  
인천광역시  100.435867

In [108]:
korea_mdf.stack()

행정구역   년도         
광주광역시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남여비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남여비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남여비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남여비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남여비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남여비율     9.970703e+01
부산광역시  2010  총인구수     2.567910e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남여비율     9.879815e+01
 

In [109]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312345  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [110]:
idx_flat = korea_mdf.reset_index(level=0)
idx_flat

행정구역      총인구수    남자인구수    여자인구수        남여비율
년도                                                 
2010  광주광역시   1454636   721780   732856   98.488653
2020  광주광역시   1455048   720060   734988   97.968946
2010  대구광역시   2511676  1255245  1256431   99.905606
2020  대구광역시   2427954  1198815  1229139   97.532907
2010  대전광역시   1503664   753648   750016  100.484256
2020  대전광역시   1471040   734441   736599   99.707032
2010  부산광역시   2567910  1773170  1794740   98.798155
2020  부산광역시   3404423  1668618  1735805   96.129346
2010  서울특별시  10312345  5111259  5201286   98.269140
2020  서울특별시   9720846  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2947217  1476813  1470404  100.435867

In [111]:
idx_flat = korea_mdf.reset_index(level=1)
idx_flat

년도      총인구수    남자인구수    여자인구수        남여비율
행정구역                                               
광주광역시  2010   1454636   721780   732856   98.488653
광주광역시  2020   1455048   720060   734988   97.968946
대구광역시  2010   2511676  1255245  1256431   99.905606
대구광역시  2020   2427954  1198815  1229139   97.532907
대전광역시  2010   1503664   753648   750016  100.484256
대전광역시  2020   1471040   734441   736599   99.707032
부산광역시  2010   2567910  1773170  1794740   98.798155
부산광역시  2020   3404423  1668618  1735805   96.129346
서울특별시  2010  10312345  5111259  5201286   98.269140
서울특별시  2020   9720846  4732275  4988571   94.862336
인천광역시  2010   2758296  1390356  1367940  101.638668
인천광역시  2020   2947217  1476813  1470404  100.435867

In [112]:
idx_flat = korea_mdf.reset_index(level=(0, 1))
idx_flat

행정구역    년도      총인구수    남자인구수    여자인구수        남여비율
0   광주광역시  2010   1454636   721780   732856   98.488653
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   2567910  1773170  1794740   98.798155
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10312345  5111259  5201286   98.269140
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [113]:
idx_flat.set_index(['행정구역', '년도'])

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312345  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

## 데이터 연산

In [114]:
s = pd.Series(np.random.randint(0, 10, 5))
s

0    8
1    9
2    4
3    7
4    6
dtype: int32

In [115]:
df = pd.DataFrame(np.random.randint(0, 10, (3,3)),
                  columns=['A', 'B', 'C'])
df

A  B  C
0  8  2  6
1  1  2  1
2  8  9  4

In [116]:
np.exp(s)

0    2980.957987
1    8103.083928
2      54.598150
3    1096.633158
4     403.428793
dtype: float64

In [117]:
np.cos(df * np.pi / 4)

A             B             C
0  1.000000  6.123234e-17 -1.836970e-16
1  0.707107  6.123234e-17  7.071068e-01
2  1.000000  7.071068e-01 -1.000000e+00

In [118]:
s1 = pd.Series([1, 3, 5, 7, 9], index=[0, 1, 2, 3, 4])
s2 = pd.Series([2, 4, 6, 8, 10], index=[1, 2, 3, 4, 5])
s1 + s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [121]:
s1.add(s2, fill_value=0) #NaN 대신에 0을 넣는다

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [123]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3,3)),
                   columns=list('ACD'))
df1

A   C   D
0  10   1  17
1   0  10  17
2   5   6  15

In [124]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5,5)),
                   columns=list('BAECD'))
df2

B   A  E   C   D
0   1  17  4  13   3
1   8  10  8   7   0
2   6   9  1   7  17
3  17   9  1  10  18
4  10  16  2   1   3

In [125]:
df1 + df2

A   B     C     D   E
0  27.0 NaN  14.0  20.0 NaN
1  10.0 NaN  17.0  17.0 NaN
2  14.0 NaN  13.0  32.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [129]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value = fvalue)

A     B     C     D     E
0  27.0  10.0  14.0  20.0  13.0
1  10.0  17.0  17.0  17.0  17.0
2  14.0  15.0  13.0  32.0  10.0
3  18.0  26.0  19.0  27.0  10.0
4  25.0  19.0  10.0  12.0  11.0

### 연산자 범용 함수


#### add()

In [130]:
a = np.random.randint(1, 10, size=(3,3))
a

array([[8, 8, 6],
       [7, 4, 7],
       [7, 1, 6]])

In [131]:
a + a[0]

array([[16, 16, 12],
       [15, 12, 13],
       [15,  9, 12]])

In [132]:
df = pd.DataFrame(a, columns=list('ABC'))
df

A  B  C
0  8  8  6
1  7  4  7
2  7  1  6

In [137]:
df + df.iloc[2]

A  B   C
0  15  9  12
1  14  5  13
2  14  2  12

In [134]:
df.add(df.iloc[0])

A   B   C
0  16  16  12
1  15  12  13
2  15   9  12

#### sub() / subtract()

In [138]:
a

array([[8, 8, 6],
       [7, 4, 7],
       [7, 1, 6]])

In [139]:
a - a[0]

array([[ 0,  0,  0],
       [-1, -4,  1],
       [-1, -7,  0]])

In [140]:
df

A  B  C
0  8  8  6
1  7  4  7
2  7  1  6

In [141]:
df - df.iloc[0]

A  B  C
0  0  0  0
1 -1 -4  1
2 -1 -7  0

In [142]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1 -1 -4  1
2 -1 -7  0

In [146]:
df.subtract(df['B'], axis=0) #axis=0은 열방향

A  B  C
0  0  0 -2
1  3  0  3
2  6  0  5

#### mul() / multply()




In [147]:
a

array([[8, 8, 6],
       [7, 4, 7],
       [7, 1, 6]])

In [148]:
a * a[0]

array([[64, 64, 36],
       [56, 32, 42],
       [56,  8, 36]])

In [149]:
df

A  B  C
0  8  8  6
1  7  4  7
2  7  1  6

In [150]:
df * df.iloc[1]

A   B   C
0  56  32  42
1  49  16  49
2  49   4  42

In [151]:
df.mul(df.iloc[1])

A   B   C
0  56  32  42
1  49  16  49
2  49   4  42

In [152]:
df.multiply(df.iloc[1])

A   B   C
0  56  32  42
1  49  16  49
2  49   4  42

#### truediv() /  div() / divide() / floordiv()

In [153]:
a

array([[8, 8, 6],
       [7, 4, 7],
       [7, 1, 6]])

In [154]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [0.875     , 0.5       , 1.16666667],
       [0.875     , 0.125     , 1.        ]])

In [155]:
df

A  B  C
0  8  8  6
1  7  4  7
2  7  1  6

In [156]:
df / df.iloc[0]

A      B         C
0  1.000  1.000  1.000000
1  0.875  0.500  1.166667
2  0.875  0.125  1.000000

In [157]:
df.truediv(df.iloc[0])

A      B         C
0  1.000  1.000  1.000000
1  0.875  0.500  1.166667
2  0.875  0.125  1.000000

In [158]:
df.div(df.iloc[1])

A     B         C
0  1.142857  2.00  0.857143
1  1.000000  1.00  1.000000
2  1.000000  0.25  0.857143

In [159]:
df.divide(df.iloc[2])

A    B         C
0  1.142857  8.0  1.000000
1  1.000000  4.0  1.166667
2  1.000000  1.0  1.000000

In [160]:
a // a[0]

array([[1, 1, 1],
       [0, 0, 1],
       [0, 0, 1]], dtype=int32)

In [161]:
df.floordiv(df.iloc[0])

A  B  C
0  1  1  1
1  0  0  1
2  0  0  1

#### mod()

In [162]:
a

array([[8, 8, 6],
       [7, 4, 7],
       [7, 1, 6]])

In [163]:
a % a[0]

array([[0, 0, 0],
       [7, 4, 1],
       [7, 1, 0]], dtype=int32)

In [164]:
df

A  B  C
0  8  8  6
1  7  4  7
2  7  1  6

In [165]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  7  4  1
2  7  1  0

#### pow()

In [166]:
a

array([[8, 8, 6],
       [7, 4, 7],
       [7, 1, 6]])

In [167]:
a ** a[0]

array([[16777216, 16777216,    46656],
       [ 5764801,    65536,   117649],
       [ 5764801,        1,    46656]], dtype=int32)

In [168]:
df.pow(df.iloc[0])

A         B       C
0  16777216  16777216   46656
1   5764801     65536  117649
2   5764801         1   46656

In [169]:
row = df.iloc[0, ::2]
row

A    8
C    6
Name: 0, dtype: int32

In [170]:
df - row

A   B    C
0  0.0 NaN  0.0
1 -1.0 NaN  1.0
2 -1.0 NaN  0.0

### 정렬(Sort)

In [171]:
s = pd.Series(range(5), index=['A', 'D', 'B', 'C', 'E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [172]:
s.sort_index() #인덱스별 정렬

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [173]:
s.sort_values() #값으로 정렬

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [174]:
df = pd.DataFrame(np.random.randint(0, 10, (4,4)),
                  index = [2, 4, 1, 3],
                  columns = list('BDAC'))
df

B  D  A  C
2  8  2  1  0
4  5  3  0  1
1  2  5  6  5
3  6  5  0  5

In [175]:
df.sort_index() #인덱스별 정렬

B  D  A  C
1  2  5  6  5
2  8  2  1  0
3  6  5  0  5
4  5  3  0  1

In [183]:
df.sort_index(axis = 1) #축을 열로 지정하여 ABCD순으로 나옴

A  B  C  D
2  1  8  0  2
4  0  5  1  3
1  6  2  5  5
3  0  6  5  5

In [181]:
# df.sort_values() 2차원이므로 column(열)을 하나 지정해줘야 함
df.sort_values(by = ['A', 'B']) # A 정렬 후 B 정렬

B  D  A  C
4  5  3  0  1
3  6  5  0  5
2  8  2  1  0
1  2  5  6  5

In [182]:
df.sort_values(by = 'C')

B  D  A  C
2  8  2  1  0
4  5  3  0  1
1  2  5  6  5
3  6  5  0  5

### 순위(Ranking)


In [184]:
s = pd.Series([-2, 4, 7, 3, 0, 7, 5, -4, 2, 6])
s

0   -2
1    4
2    7
3    3
4    0
5    7
6    5
7   -4
8    2
9    6
dtype: int64

In [185]:
s.rank()

0    2.0
1    6.0
2    9.5
3    5.0
4    3.0
5    9.5
6    7.0
7    1.0
8    4.0
9    8.0
dtype: float64

In [186]:
s.rank(method = 'first') #테이블 내의 위치에 따라 순위 지정

0     2.0
1     6.0
2     9.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

In [187]:
s.rank(method = 'max') #같은 값을 가지는 그룹을 높은 순위로 지정

0     2.0
1     6.0
2    10.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

### 고성능 연산

## 데이터 결합

### Concat() / Append()

### 병합과 조인

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


### GroupBy 연산

### 피벗 테이블(Pivot Table)


### 범주형(Categorical) 데이터


## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly